import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { PopupProvider } from '@/shared/ui/Popup';
import { ToastProvider } from '@/shared/ui/Toast';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ToastProvider>
          <PopupProvider>{children}</PopupProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
